<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <Platforms>x64;ARM64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RepositoryUrl>https://github.com/hrxlou/Glassline.WinUI</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>Glassline.WinUI contributors</Authors>
    <Copyright>Copyright (c) Glassline.WinUI contributors</Copyright>
  </PropertyGroup>
</Project>
